name: CD - Deploy to ECS

on:
  workflow_run:
    workflows: ["CI - Build & Push"]
    types: [completed]
    branches: [main]

concurrency:
  group: deploy-production
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}-repo
  ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}-cluster
  ECS_SERVICE: ${{ vars.ECS_SERVICE }}-service
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME}}-container

jobs:
  build:
    name: Build push & deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          soft_fail: true

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}