name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      terraform_destroy:
        description: 'Type "Destroy" to confirm. Infrastruture will be deleted & cannot be undone.'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: ${{ github.event.inputs.terraform_destroy == 'DESTROY' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/Checkout@v4

    - name: setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ var.AWS_REGION }}
  